### ISSUE TITLE
im going to take away your feet

### ISSUE THREAD

**Issue by MESYETI** [jeffalo/browser-extension-slash-userscript-policy#4]
say bye bye to your feet

**Comment by CubeyTheCube** [comment]
oh no please dont

**Comment by pufferfish101007** [comment]
Good idea
Shpuld be added

**Comment by CubeyTheCube** [comment]
> Good idea
> Shpuld be added

ill make a PR

**Comment by pufferfish101007** [comment]
> > Good idea
> > Shpuld be added
> 
> ill make a PR

Thanks

**Comment by CubeyTheCube** [comment]
> > > Good idea
> > > Shpuld be added
> > 
> > 
> > ill make a PR
> 
> Thanks

yw 😃
